spring.application.name=digital-subsidy-grant-platform

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=eKoTpHvlshdw9L074KtLVqVgsgTZ1ipXMRBnKrIwfRA= 
jwt.expiration=86400000