package com.infosys.subsidy.enums;

public enum DocumentType {
    AADHAAR_CARD,
    INCOME_CERTIFICATE,
    MARKSHEET,
    BONAFIDE_CERTIFICATE,
    COLLEGE_ID_CARD,
    CASTE_CERTIFICATE,
    LAND_CERTIFICATE,
    PROPERTY_DOCUMENT,
    LAND_RECORD_7_12,
    BANK_PASSBOOK,
    RESIDENCE_CERTIFICATE,
    OTHER
}
